### ISSUE TITLE
Falta describir cada imagen en el atributo alt .

### ISSUE THREAD

**Issue by StefAranzazu** [ederdon/Simple-Instagram-Photo-Feed-with-HTML-CSS#1]
Actualmente solo dicen "photo post x", hay que describir la imagen en si.

**Comment by eder01gp** [comment]
Las imagenes se generan randomly asi que no puedo definirla con anterioridad. Lo pregunté en el discord a Manu y dijo que para el año que viene lo prohibirá ajajja

**Comment by StefAranzazu** [comment]
Que listo! Jajaja todo perfecto entonces
